export const characterDefs = [
  [
    "crusoe",
    "Robinson Crusoe",
    "The narrator, an English merchant and castaway whose restless appetite for travel is reshaped by survival, faith, and long isolation.",
  ],
  [
    "father",
    "Crusoe’s Father",
    "A prosperous retired merchant of Bremen origin who urges his youngest son toward the secure middle station of life.",
  ],
  [
    "mother",
    "Crusoe’s Mother",
    "Crusoe’s English mother, who refuses to support a voyage that her husband believes will ruin their son.",
  ],
  [
    "friend",
    "The Hull Friend",
    "A shipmaster’s son whose invitation enables Crusoe’s secret first voyage and who later urges him to return home.",
  ],
  [
    "guinea-captain",
    "The Guinea Captain",
    "An honest London master who teaches Crusoe seamanship and trade and safeguards his early investment.",
  ],
  [
    "sallee-master",
    "The Sallee Captain",
    "The corsair captain who enslaves Crusoe and employs him in household work and fishing.",
  ],
  [
    "xury",
    "Xury",
    "A young fellow captive who escapes with Crusoe, proves courageous along the African coast, and enters the Portuguese captain’s service.",
  ],
  [
    "moor",
    "Ismael",
    "The adult Moor sent fishing with Crusoe and Xury, expelled from the boat when Crusoe makes his escape.",
  ],
  [
    "portuguese-captain",
    "The Portuguese Captain",
    "The generous master who rescues Crusoe at sea, helps establish his Brazilian fortune, and later restores it honestly.",
  ],
  [
    "wells",
    "Wells",
    "A neighbouring Brazilian planter of English parentage whose progress Crusoe uses to measure his own.",
  ],
  [
    "planters",
    "The Brazilian Planters",
    "Crusoe’s neighbours and partners in the proposed Guinea voyage for enslaved labourers.",
  ],
  [
    "ship-crew",
    "The Wrecked Ship’s Company",
    "The master, sailors, and boy lost when the Brazil-to-Guinea expedition founders off the island.",
  ],
  [
    "carib-raiders",
    "The Visiting Warriors",
    "Armed mainland parties who bring captives to the island for ritual killing and consumption.",
  ],
  [
    "friday",
    "Friday",
    "The captive rescued by Crusoe who becomes his companion, pupil, interpreter, fellow labourer, and courageous ally.",
  ],
  [
    "spaniard",
    "The Spaniard",
    "A European castaway rescued from a visiting party who helps plan contact with his stranded companions.",
  ],
  [
    "friday-father",
    "Friday’s Father",
    "An elder rescued beside the Spaniard whose survival reconnects Friday with his family and mainland people.",
  ],
  [
    "english-captain",
    "The English Captain",
    "The lawful commander marooned by his mutinous crew, restored through an alliance with Crusoe.",
  ],
  [
    "mate",
    "The Captain’s Mate",
    "A loyal officer landed as a prisoner with his captain who helps defeat the mutineers and recover the ship.",
  ],
  [
    "passenger",
    "The English Passenger",
    "A loyal passenger marooned with the captain and mate who joins the counterattack.",
  ],
  [
    "mutineers",
    "The English Mutineers",
    "The divided sailors who seize the English ship and later search the island for their missing boat crews.",
  ],
  [
    "boatswain",
    "The Mutinous Boatswain",
    "The most dangerous leader of the second landing party, killed when he refuses surrender.",
  ],
  [
    "will-atkins",
    "Will Atkins",
    "A prominent mutineer spared from execution and left among the island’s new settlers.",
  ],
  [
    "guide",
    "The Pyrenean Guide",
    "The local leader who takes Crusoe’s party through the snowbound mountain route and is mauled by wolves.",
  ],
  [
    "widow",
    "The Captain’s Widow",
    "Crusoe’s faithful English steward and friend, entrusted with his early money and rewarded after his return.",
  ],
];

export const locationDefs = [
  [
    "york-home",
    "world",
    "Crusoe Family Home, York",
    "A comfortable merchant household where Crusoe is educated and warned against abandoning a secure future.",
  ],
  [
    "north-sea",
    "world",
    "North Sea Passage",
    "The exposed coastal water between Hull and London where Crusoe first experiences a storm.",
  ],
  [
    "yarmouth-roads",
    "world",
    "Yarmouth Roads",
    "A normally sheltered anchorage where an exceptional gale overwhelms Crusoe’s first ship.",
  ],
  [
    "london",
    "world",
    "London",
    "The commercial port where Crusoe finds patronage, learns the Guinea trade, and entrusts money to a captain’s widow.",
  ],
  [
    "guinea-coast",
    "world",
    "Guinea Coast",
    "The West African trading coast visited during Crusoe’s successful merchant voyage.",
  ],
  [
    "sallee",
    "world",
    "Sallee",
    "The Moroccan corsair port where Crusoe is held in slavery for two years.",
  ],
  [
    "sallee-harbor",
    "world",
    "Sallee Harbour",
    "The fishing waters from which Crusoe and Xury steal their master’s longboat.",
  ],
  [
    "african-coast",
    "world",
    "Atlantic Coast of Africa",
    "A sparsely known coast of anchorages, rivers, wildlife, and communities followed by the escaping longboat.",
  ],
  [
    "atlantic-passage",
    "world",
    "Atlantic Passage",
    "The ocean routes connecting Africa, Brazil, the island, and Europe across Crusoe’s voyages.",
  ],
  [
    "brazil-plantation",
    "world",
    "Crusoe’s Brazilian Plantation",
    "A sugar-growing estate near Bahia that becomes the source of Crusoe’s eventual fortune.",
  ],
  [
    "island-gateway",
    "world",
    "Crusoe’s Island",
    "The remote island near the South American mainland where the wreck leaves Crusoe isolated for twenty-eight years.",
  ],
  [
    "wreck-site",
    "island",
    "The Wreck and Landing Shore",
    "The eastern reef, tidal creek, and beach where Crusoe survives and repeatedly salvages the grounded ship.",
  ],
  [
    "island-shore",
    "island",
    "First Night Shore",
    "Open ground near the landing where Crusoe spends his first night in a tree.",
  ],
  [
    "island-castle",
    "island",
    "The Castle",
    "Crusoe’s concealed palisade, tent, cave storehouse, and principal home beside fresh water.",
  ],
  [
    "country-bower",
    "island",
    "The Country Bower",
    "A shaded inland retreat set among fruit, grapes, and the island’s more fertile ground.",
  ],
  [
    "island-interior",
    "island",
    "Wooded Interior",
    "Hills, valleys, and savannah crossed during Crusoe’s surveys and hunting journeys.",
  ],
  [
    "cornfields",
    "island",
    "Barley and Rice Fields",
    "Small enclosed plots where salvaged grains are slowly multiplied into dependable harvests.",
  ],
  [
    "great-canoe",
    "island",
    "The Great Canoe",
    "The construction site of an enormous dugout left stranded far from the water.",
  ],
  [
    "island-coast",
    "island",
    "Outer Coast and Current",
    "The island’s exposed capes and offshore currents, navigable only with close attention to tides.",
  ],
  [
    "goat-pasture",
    "island",
    "Tame Goat Enclosure",
    "A fenced meadow where captured goats become a renewable herd for meat and milk.",
  ],
  [
    "boat-harbor",
    "island",
    "Canoe Harbour",
    "A protected creek used to conceal and maintain Crusoe’s smaller canoe.",
  ],
  [
    "footprint-beach",
    "island",
    "Footprint Beach",
    "A quiet sandy shore where one human track overturns years of assumed solitude.",
  ],
  [
    "hidden-pasture",
    "island",
    "Hidden Goat Pasture",
    "A remote second enclosure intended to preserve part of the herd if strangers discover the castle.",
  ],
  [
    "cannibal-shore",
    "island",
    "South-west Landing Shore",
    "A recurring mainland landing place marked by fires and the remains of captives.",
  ],
  [
    "lookout-hill",
    "island",
    "Western Lookout",
    "High ground from which Crusoe watches the landing shore and the distant mainland.",
  ],
  [
    "hidden-cave",
    "island",
    "The Hidden Cave",
    "A deep, defensible chamber behind a narrow rock opening, stocked as an emergency retreat.",
  ],
  [
    "spanish-wreck",
    "island",
    "Spanish Wreck",
    "A European vessel stranded on offshore rocks beyond the reach of its drowned crew.",
  ],
  [
    "friday-rescue-shore",
    "island",
    "Friday’s Creek",
    "The creek and woodland crossed during Friday’s flight from his captors.",
  ],
  [
    "boat-yard",
    "island",
    "Seaworthy Canoe Yard",
    "A waterside worksite where Crusoe and Friday build and rig a canoe for the mainland crossing.",
  ],
  [
    "mutineer-landing",
    "island",
    "English Boat Landing",
    "The beach where mutineers maroon their captain and later search for missing comrades.",
  ],
  [
    "english-ship",
    "world",
    "The Recovered English Ship",
    "The vessel reclaimed from its mutinous crew and used for Crusoe’s return to England.",
  ],
  [
    "lisbon",
    "world",
    "Lisbon",
    "The Portuguese capital where Crusoe finds his former rescuer and recovers his Brazilian estate.",
  ],
  [
    "iberian-road",
    "world",
    "Road Across Iberia",
    "The overland route chosen from Lisbon toward France to avoid another sea voyage.",
  ],
  [
    "pyrenees",
    "world",
    "Pyrenean Pass",
    "A snowbound mountain and forest route threatened by bears, wolves, and severe winter weather.",
  ],
  [
    "england",
    "world",
    "England After the Return",
    "Crusoe’s restored home country, where he settles his fortune and establishes a family.",
  ],
];

export const itemDefs = [
  [
    "guinea-gold",
    "Guinea Trading Gold",
    "The profit and gold dust from Crusoe’s first successful trading voyage.",
    "coins",
  ],
  [
    "escape-longboat",
    "The Sallee Longboat",
    "The provisioned fishing boat in which Crusoe and Xury escape captivity.",
    "boat",
  ],
  [
    "firearms",
    "Salvaged Firearms",
    "Muskets, fowling-pieces, and pistols recovered from the wreck and preserved for hunting and defence.",
    "weapon",
  ],
  [
    "gunpowder",
    "Gunpowder Stores",
    "The finite stock of powder divided among dry containers after a lightning storm reveals the danger of one magazine.",
    "container",
  ],
  [
    "tools",
    "Salvaged Tools",
    "Axes, saws, ironwork, and improvised implements that make construction and agriculture possible.",
    "tool",
  ],
  [
    "calendar-post",
    "The Calendar Post",
    "A squared timber marked with daily, weekly, monthly, and yearly notches from the date of the wreck.",
    "document",
  ],
  [
    "journal",
    "Crusoe’s Journal",
    "The dated record of the first island year, written until the salvaged ink begins to fail.",
    "book",
  ],
  [
    "bible",
    "The Salvaged Bible",
    "One of the books recovered from the ship, read during illness and throughout Crusoe’s later solitude.",
    "book",
  ],
  [
    "grain",
    "Barley and Rice Seed",
    "A few surviving grains accidentally sprouted and patiently multiplied into staple crops.",
    "food",
  ],
  [
    "goatskins",
    "Goatskin Clothing and Umbrella",
    "Weathered handmade garments and a folding shade adapted to the island climate.",
    "clothing",
  ],
  [
    "seaworthy-canoe",
    "The Seaworthy Canoe",
    "The smaller dugout that Crusoe and Friday launch, rig, and provision for an intended mainland crossing.",
    "boat",
  ],
  [
    "plantation-accounts",
    "Brazilian Plantation Accounts",
    "Letters, legal accounts, and bills of exchange proving the survival and value of Crusoe’s estate.",
    "document",
  ],
];

export const relationshipDefs = [
  [
    "crusoe",
    "father",
    "son and father",
    5,
    "positive",
    "Affection is strained by Crusoe’s rejection of his father’s counsel.",
  ],
  [
    "crusoe",
    "mother",
    "son and mother",
    4,
    "positive",
    "She cares for Crusoe but refuses to assist the voyage opposed by his father.",
  ],
  [
    "crusoe",
    "xury",
    "fellow escapees",
    4,
    "positive",
    "Shared danger builds trust, though Crusoe later accepts Xury’s sale into conditional service.",
  ],
  [
    "crusoe",
    "portuguese-captain",
    "beneficiary and benefactor",
    5,
    "positive",
    "Repeated generosity and honesty connect Crusoe’s rescue to his restored fortune.",
  ],
  [
    "crusoe",
    "friday",
    "companions",
    5,
    "positive",
    "A relationship begun under unequal authority grows through labour, teaching, trust, and mutual rescue.",
  ],
  [
    "friday",
    "friday-father",
    "son and father",
    5,
    "positive",
    "Their unexpected reunion restores a family bond Friday believed lost.",
  ],
  [
    "crusoe",
    "spaniard",
    "allies",
    4,
    "positive",
    "The rescued Spaniard joins the island household and helps plan contact with other castaways.",
  ],
  [
    "crusoe",
    "english-captain",
    "allies",
    5,
    "positive",
    "Each offers the other deliverance: Crusoe helps recover the ship and the captain carries him home.",
  ],
  [
    "english-captain",
    "mate",
    "captain and loyal officer",
    5,
    "positive",
    "The mate remains loyal through marooning and the counterattack.",
  ],
  [
    "crusoe",
    "widow",
    "friends and financial stewards",
    5,
    "positive",
    "Each safeguards the other’s interests across Crusoe’s long absence.",
  ],
];

export const threadDefs = [
  [
    "wandering",
    "The Cost of Wandering",
    "Crusoe repeatedly exchanges secure circumstances for uncertain ventures.",
  ],
  [
    "survival",
    "Making a Life from the Wreck",
    "Salvage, invention, agriculture, and husbandry turn immediate survival into durable settlement.",
  ],
  [
    "providence",
    "Providence and Repentance",
    "Disaster, gratitude, fear, and scripture reshape Crusoe’s interpretation of his life.",
  ],
  [
    "escape",
    "The Hope of Escape",
    "Ships, boats, currents, distant land, and companions repeatedly alter the possibility of leaving.",
  ],
  [
    "encounter",
    "Signs of Other People",
    "Footprints, remains, wrecks, and landings transform solitude into fearful and then cooperative encounter.",
  ],
  [
    "plantation",
    "The Brazilian Estate",
    "The plantation abandoned in 1659 silently grows into the fortune restored after Crusoe’s return.",
  ],
  [
    "colony",
    "From Castaway to Colony",
    "The solitary household becomes a community and eventually a supplied island settlement.",
  ],
];

export const motifDefs = [
  [
    "storms",
    "Storms and Currents",
    "Wind, wreck, tide, and current repeatedly expose the limits of intention.",
  ],
  [
    "accounts",
    "Accounts and Reckoning",
    "Ledgers, calendars, journals, and moral balances give form to long stretches of experience.",
  ],
  [
    "labour",
    "Tools and Patient Labour",
    "Awkward repeated work converts salvaged material and natural resources into a human environment.",
  ],
  [
    "enclosures",
    "Walls and Enclosures",
    "Palisades, caves, fences, and hidden groves promise safety while expressing fear and possession.",
  ],
  [
    "signs",
    "Tracks, Smoke, and Signals",
    "Small traces reveal unseen people and force Crusoe to revise what he thinks he knows.",
  ],
  [
    "weapons",
    "Guns and Finite Powder",
    "Firearms confer extraordinary force, but their ammunition diminishes and their use changes with human contact.",
  ],
  [
    "mastery",
    "Mastery and Service",
    "The language of ownership, kingship, slavery, loyalty, and service runs through Crusoe’s changing households.",
  ],
];
