export const chapterLedger = [
  [1,"O Ramalhete e a história dos Maias","A instalação no Ramalhete abre a memória de Afonso, Pedro e Maria Monforte."],
  [2,"A ruína de Pedro da Maia","O casamento, a fuga de Maria Monforte e a morte de Pedro entregam Carlos ao avô."],
  [3,"A educação em Santa Olávia","Afonso cria Carlos segundo ideias modernas, em contraste com a educação de Eusebiozinho."],
  [4,"Coimbra, medicina e regresso","Carlos atravessa a vida académica, forma-se e regressa a Lisboa cheio de projetos."],
  [5,"A vida no Ramalhete","O consultório, os amigos e os hábitos elegantes revelam a dispersão inicial de Carlos."],
  [6,"O jantar no Hotel Central","Carlos vê Maria Eduarda e participa num jantar que expõe a superficialidade das elites."],
  [7,"Visitas e aproximações","As relações sociais de Carlos estreitam-se enquanto cresce a curiosidade por Maria Eduarda."],
  [8,"A jornada a Sintra","Carlos procura em vão Maria Eduarda e encontra no passeio um retrato cómico da sociedade."],
  [9,"Paixões e encontros","A ligação com a condessa de Gouvarinho complica-se e Carlos aproxima-se da família Castro Gomes."],
  [10,"As corridas do hipódromo","O espetáculo mundano evidencia provincianismo, rivalidades e o fascínio de Carlos."],
  [11,"O amor declarado","A doença de Rosa conduz Carlos à casa de Maria Eduarda e à confissão do amor de ambos."],
  [12,"A intimidade e os Gouvarinho","O romance floresce, enquanto um jantar aristocrático satiriza política e cultura."],
  [13,"A Toca e o confronto","Carlos instala Maria Eduarda nos Olivais e enfrenta a maledicência de Dâmaso."],
  [14,"Revelações do passado","Castro Gomes desfaz a história conjugal de Maria, que conta finalmente a sua vida a Carlos."],
  [15,"A carta de Dâmaso","A imprensa transforma o escândalo em mercadoria e Carlos procura reparar a honra de Maria."],
  [16,"O sarau e a caixa de Guimarães","A noite no Teatro da Trindade culmina na entrega dos documentos que revelam o parentesco."],
  [17,"A verdade e a morte de Afonso","Carlos recebe a prova de que Maria é sua irmã, falha perante a verdade e perde o avô."],
  [18,"Dez anos depois","Carlos e Ega regressam ao Ramalhete e reconhecem, entre ironia e melancolia, a vida desperdiçada."],
].map(([number,title,synopsis])=>({number,title,synopsis}));
