import assert from "node:assert/strict";import crypto from "node:crypto";import fs from "node:fs";import path from "node:path";import {narrativeText} from "./source-text.mjs";
const a=fs.readFileSync("example/Os Maias.pwk"),b=fs.readFileSync("public/library/os-maias.pwk");assert(a.equals(b),"As duas cópias PWK diferem");const d=JSON.parse(a),ids=x=>new Set(x.map(y=>y.id)),chars=ids(d.characters),events=ids(d.events),locs=ids(d.locationMarkers),maps=ids(d.mapLayers),items=ids(d.items),blobs=ids(d.blobs);
assert.equal(d.chapters.length,18);assert.equal(d.events.length,72);assert.equal(d.sceneTexts.length,72);assert.equal(d.timelines.length,1);assert.equal(d.sceneTexts.map(x=>x.text).join("\n\n"),narrativeText,"O manuscrito não é lossless");assert.equal(d.world.readingMode,true);assert.equal(d.world.theme,"historical");assert.equal(d.world.calendar.startYear,1820);
for(const e of d.events){assert(locs.has(e.locationMarkerId),`Local inexistente: ${e.id}`);assert(e.tension>=1&&e.tension<=5);assert(e.travelDays>=0);assert(Number.isInteger(e.inWorldTime));assert(e.involvedCharacterIds.every(x=>chars.has(x)));assert(e.involvedItemIds.every(x=>items.has(x)));const s=d.characterSnapshots.filter(x=>x.eventId===e.id);assert.equal(s.length,e.involvedCharacterIds.length,`Snapshots: ${e.id}`);assert.deepEqual(new Set(s.map(x=>x.characterId)),new Set(e.involvedCharacterIds));assert.equal(new Set(s.map(x=>x.statusNotes)).size,s.length);}
for(const s of d.characterSnapshots){assert(chars.has(s.characterId));assert(events.has(s.eventId));assert(locs.has(s.currentLocationMarkerId));assert(maps.has(s.currentMapLayerId));assert(s.statusNotes.length>45);assert(!/ongoing context|state carried|not yet directly involved|toma parte ativa|papel que desempenha/i.test(s.statusNotes));}
assert(d.events[0].inWorldTime>d.events[1].inWorldTime,"A abertura de 1875 deve anteceder narrativamente a analepse, mas surgir depois dela no calendário");assert(d.events.at(-1).inWorldTime>d.events.at(-5).inWorldTime,"O epílogo de 1887 deve surgir depois da ação principal");
for(const c of d.characters){assert(d.characterSnapshots.some(x=>x.characterId===c.id),`Nunca presente: ${c.name}`);assert(blobs.has(c.portraitImageId));}
for(const l of d.locationMarkers){assert(maps.has(l.mapLayerId));assert(blobs.has(l.imageId));assert(l.x>=0&&l.x<=1536&&l.y>=0&&l.y<=1024);assert(l.description.length>=45);}
for(const m of d.mapLayers){assert(blobs.has(m.imageId));assert.equal(d.locationMarkers.filter(x=>x.linkedMapLayerId===m.id).length,m.parentMapId?1:0,`Gateway: ${m.name}`);assert(d.locationMarkers.some(x=>x.mapLayerId===m.id),`Mapa vazio: ${m.name}`);}
for(const r of d.mapRoutes){assert(Array.isArray(r.waypoints));assert(r.waypoints.every(x=>locs.has(x)));}
for(const r of d.relationships){assert(chars.has(r.characterAId)&&chars.has(r.characterBId)&&events.has(r.createdAtEventId));}
const hashes=new Map();for(const blob of d.blobs){const p=path.join("public",blob.url);assert(fs.existsSync(p),`Asset em falta: ${p}`);const bytes=fs.readFileSync(p);assert(bytes.length>30000,`Asset suspeito: ${p}`);const h=crypto.createHash("sha256").update(bytes).digest("hex");assert(!hashes.has(h),`Asset duplicado: ${p} / ${hashes.get(h)}`);hashes.set(h,p);}
const index=JSON.parse(fs.readFileSync("public/library/index.json")),entry=index.entries.find(x=>x.id==="os-maias");assert(entry);assert.equal(entry.dataBytes,b.length);assert.deepEqual(entry.counts,{characters:d.characters.length,chapters:d.chapters.length,events:d.events.length,locations:d.locationMarkers.length});
console.log({chapters:18,events:72,words:d.sceneTexts.reduce((n,x)=>n+x.wordCount,0),snapshots:d.characterSnapshots.length,maps:d.mapLayers.length,locations:d.locationMarkers.length,characters:d.characters.length,items:d.items.length,assets:d.blobs.length,lossless:true});
