/** Source-grounded chapter ledger. Titles are editorial signposts. */
export const chapterLedger = [
  ["Lockwood Meets His Landlord", "Lockwood visits the forbidding Wuthering Heights and meets Heathcliff."],
  ["Snowbound at Wuthering Heights", "A second visit reveals Cathy, Hareton, and the household's hostile mysteries before snow traps Lockwood."],
  ["The Haunted Chamber", "In Catherine's old room Lockwood reads her diary, dreams of her ghost, and witnesses Heathcliff's anguish."],
  ["The Foundling from Liverpool", "Nelly begins the family history with Mr Earnshaw bringing the orphan Heathcliff home."],
  ["The Master's Death", "Mr Earnshaw declines and dies while Catherine and Heathcliff remain inseparable."],
  ["Hindley Returns", "Hindley returns with Frances, degrades Heathcliff, and separates him from Catherine."],
  ["Christmas at the Heights", "Catherine returns polished from the Grange while Heathcliff suffers humiliation before the Lintons."],
  ["Birth and Bereavement", "Hareton is born, Frances dies, and Hindley's grief turns the Heights violent."],
  ["Catherine's Choice", "Catherine accepts Edgar yet confesses her identity is bound to Heathcliff, who overhears only her rejection of marrying him."],
  ["Heathcliff Returns", "After three years Heathcliff returns transformed, unsettling Catherine, Edgar, Hindley, and Isabella."],
  ["The Houses Divide", "Heathcliff exploits Hindley and Isabella's infatuation while a confrontation drives him from the Grange."],
  ["Catherine's Fever", "Catherine's protest becomes delirium as Isabella elopes with Heathcliff."],
  ["Isabella at the Heights", "Isabella writes to Nelly from a brutal marriage and asks whether Heathcliff is human."],
  ["Nelly Visits Isabella", "At the Heights Heathcliff compels Nelly to arrange a secret meeting with Catherine."],
  ["The Last Meeting", "Heathcliff and Catherine reunite in accusation and desperate love before Edgar returns."],
  ["Catherine's Death", "Catherine gives birth to young Cathy and dies; Heathcliff begs her spirit to haunt him."],
  ["Deaths and Departures", "Isabella escapes, Hindley dies, and Heathcliff takes possession of Hareton and the Heights."],
  ["Cathy's Sheltered Childhood", "Young Cathy grows up at the Grange and discovers the Heights during an unauthorized excursion."],
  ["Linton Arrives", "Isabella's death brings the sickly Linton Heathcliff to the Grange."],
  ["A Son Claimed", "Heathcliff demands Linton and Nelly delivers the frightened boy to the Heights."],
  ["Cousins on the Moor", "Cathy meets Hareton and Linton, and Heathcliff begins drawing her toward his son."],
  ["Edgar's Illness", "Cathy is confined while Edgar grows ill, then meets Heathcliff on the moor and is urged to visit Linton."],
  ["The First Secret Visit", "Cathy finds Linton weak and petulant but begins a clandestine correspondence and visit."],
  ["Nelly Discovers the Courtship", "Nelly follows Cathy to the Heights, witnesses the cousins' strained intimacy, and ends the secret visits."],
  ["A Plan for Marriage", "Years later Edgar's decline makes Cathy's future urgent while Heathcliff presses Linton's claim."],
  ["Meeting at the Boundary", "Cathy and Nelly meet the failing Linton, whose fear reveals he acts under coercion."],
  ["Prisoners at the Heights", "Heathcliff traps Cathy and Nelly and forces Cathy to remain until she marries Linton."],
  ["Escape and Bereavement", "Cathy escapes in time to attend Edgar's deathbed, then is taken back as Linton's wife."],
  ["Catherine's Grave", "Heathcliff tells Nelly how he disturbed Catherine's grave and still feels her presence."],
  ["Zillah's Account", "Nelly learns how Linton died and how the widowed Cathy was isolated at the Heights."],
  ["Lockwood Says Farewell", "Lockwood visits the Heights before leaving Yorkshire and sees Cathy and Hareton at odds."],
  ["A Changed Household", "Returning months later, Lockwood hears how Cathy began teaching Hareton and their affection grew."],
  ["Heathcliff Loses His Purpose", "Heathcliff abandons revenge as the younger pair evoke the past and his fixation consumes him."],
  ["Peace on the Moors", "Heathcliff dies, Cathy and Hareton plan their marriage, and Lockwood visits the three graves."],
].map(([title, synopsis], index) => ({ number: index + 1, title, synopsis }));
